name: gql_generator
description: GraphQL File Generator
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  args: ^2.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables: 
  gql_generator: