name: gql_generator
description: GraphQL File Generator
version: 1.3.2

environment:
  sdk: '>=3.0.0'

dependencies:
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2

executables: 
  gql_generator: